# Generated by Django 5.2.4 on 2025-11-11 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[("user", "Користувач"), ("admin", "Адміністратор")],
                default="user",
                max_length=10,
            ),
        ),
    ]
